/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamCalendarRouteImport } from './routes/team-calendar'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FoodRouteImport } from './routes/food'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as CanteenOrdersRouteImport } from './routes/canteen-orders'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'

const TeamCalendarRoute = TeamCalendarRouteImport.update({
  id: '/team-calendar',
  path: '/team-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteenOrdersRoute = CanteenOrdersRouteImport.update({
  id: '/canteen-orders',
  path: '/canteen-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/canteen-orders': typeof CanteenOrdersRoute
  '/employees': typeof EmployeesRoute
  '/food': typeof FoodRoute
  '/inventory': typeof InventoryRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/team-calendar': typeof TeamCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/canteen-orders': typeof CanteenOrdersRoute
  '/employees': typeof EmployeesRoute
  '/food': typeof FoodRoute
  '/inventory': typeof InventoryRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/team-calendar': typeof TeamCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/canteen-orders': typeof CanteenOrdersRoute
  '/employees': typeof EmployeesRoute
  '/food': typeof FoodRoute
  '/inventory': typeof InventoryRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/orders': typeof OrdersRoute
  '/team-calendar': typeof TeamCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/canteen-orders'
    | '/employees'
    | '/food'
    | '/inventory'
    | '/leave'
    | '/login'
    | '/order-confirmed'
    | '/orders'
    | '/team-calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/canteen-orders'
    | '/employees'
    | '/food'
    | '/inventory'
    | '/leave'
    | '/login'
    | '/order-confirmed'
    | '/orders'
    | '/team-calendar'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/canteen-orders'
    | '/employees'
    | '/food'
    | '/inventory'
    | '/leave'
    | '/login'
    | '/order-confirmed'
    | '/orders'
    | '/team-calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  CanteenOrdersRoute: typeof CanteenOrdersRoute
  EmployeesRoute: typeof EmployeesRoute
  FoodRoute: typeof FoodRoute
  InventoryRoute: typeof InventoryRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  OrdersRoute: typeof OrdersRoute
  TeamCalendarRoute: typeof TeamCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-calendar': {
      id: '/team-calendar'
      path: '/team-calendar'
      fullPath: '/team-calendar'
      preLoaderRoute: typeof TeamCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canteen-orders': {
      id: '/canteen-orders'
      path: '/canteen-orders'
      fullPath: '/canteen-orders'
      preLoaderRoute: typeof CanteenOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  CanteenOrdersRoute: CanteenOrdersRoute,
  EmployeesRoute: EmployeesRoute,
  FoodRoute: FoodRoute,
  InventoryRoute: InventoryRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  OrdersRoute: OrdersRoute,
  TeamCalendarRoute: TeamCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
